ProyectoNaranja/AppBlog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="Blog"),
    path('categoria/<categoria_id>', views.categoria, name='categoria'),  # Lo que va entre <> está pasado por parámetro.
]

ProyectoNaranja/AppCarro/urls.py
from django.urls import path
from . import views

# Urls de la app llamada "AppNaranja". Será incluida en "urls.py" de "ProyectoNaranja".

# Namespace para facilitarnos la vida.
app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

ProyectoNaranja/AppTienda/urls.py
from django.urls import path
from . import views

# Urls de la app llamada "AppNaranja". Será incluida en "urls.py" de "ProyectoNaranja".

urlpatterns = [
    path('', views.tienda, name="Tienda"),
]

ProyectoNaranja/ProyectoNaranja/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

# Urls del proyecto.
# Incluimos las vistas de la App llamada "AppNaranja", desde el archivo "AppNaranja/urls.py".

urlpatterns = [
    path('admin/', admin.site.urls),                    # localhost:8000/admin/     --> Enlace a al Panel de admin.*
    path('', include('AppNaranja.urls')),               # localhost:8000            --> Enlace a la página principal.
    path('servicios/', include('AppServicios.urls')),   # localhost:8000/servicios  --> Enlace a la página de servicios.
    path('blog/', include('AppBlog.urls')),             # localhost:8000/blog       --> Enlace a la página del blog.
    path('contacto/', include('AppContacto.urls')),     # localhost:8000/contacto   --> Enlace a la página del formul.
    path('tienda/', include('AppTienda.urls')),         # localhost:8000/tienda     --> Enlace a la tienda web.
    path('carro/', include('AppCarro.urls')),
]

# *El usuario y contraseña del panel de administración es "root", "1234".

ProyectoNaranja/AppTienda/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre  = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)  # Se inserta de manera automática
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name        = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre         = models.CharField(max_length=50)
    categorias     = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen         = models.ImageField(upload_to="tienda", null=True, blank=True)
    precio         = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created        = models.DateTimeField(auto_now_add=True)  # Se inserta de manera automática
    updated        = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name        = "producto"
        verbose_name_plural = "productos"

    def __str__(self):
        return self.nombre

ProyectoNaranja/AppTienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda(request):
    """ Esta vista busca su plantilla HTML en 'ProyectoNaranja/AppTienda/templates/AppTienda/tienda.html' """
    productos = Producto.objects.all()
    return render(request, "AppTienda/tienda.html", {"productos": productos})

ProyectoNaranja/AppTienda/templates/carro/widget.html
<table class="table table-bordered table-light" style="margin: 5px 5px">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>€</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %} <!-- Recorremos el diccionario -->
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-primary">+</a>
                         {{value.cantidad}}
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-primary">-</a>
                    </td>
                    <td>
                        {{value.precio}} €
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos.
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} €
            </td>
        </tr>
    </tfoot>
</table>